# Generated by Django 6.0 on 2025-12-17 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Начало рассылки")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Завершение рассылки")),
                (
                    "status",
                    models.CharField(
                        choices=[("создана", "создана"), ("запущена", "запущена"), ("завершена", "завершена")],
                        default="создана",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "db_table": "mailings",
                "ordering": ["pk"],
                "permissions": [
                    ("can_view_mailing", "Can view mailing"),
                    ("can_finished_mailing", "Can finished mailing"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "topik",
                    models.CharField(
                        blank=True, default="Без темы", max_length=150, null=True, verbose_name="Тема сообщения"
                    ),
                ),
                ("text", models.TextField(blank=True, default="", null=True, verbose_name="Текст сообщения")),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "db_table": "messages",
                "ordering": ["topik"],
                "permissions": [("can_view_message", "Can view message")],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Адрес получателя")),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, default="клиент", max_length=100, null=True, verbose_name="ФИО получателя"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", max_length=150, null=True, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
                "db_table": "recipients",
                "ordering": ["email"],
                "permissions": [("can_view_recipient", "Can view recipient")],
            },
        ),
        migrations.CreateModel(
            name="SendAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attempt_datetime",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата попытки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("успешно", "успешно"), ("не успешно", "не успешно")],
                        default="не успешно",
                        max_length=10,
                        verbose_name="Статус попытки",
                    ),
                ),
                ("server_response", models.TextField(verbose_name="Ответ сервера")),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
                "db_table": "send_attempts",
                "ordering": ["status", "attempt_datetime"],
            },
        ),
    ]
